# Generated by Django 5.2.4 on 2025-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldetail',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
