# Generated by Django 5.2.4 on 2025-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_service_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
