# Generated by Django 5.2.4 on 2025-08-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
